# Generated by Django 3.2 on 2021-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_price', models.IntegerField()),
                ('plan_desc', models.CharField(max_length=255)),
                ('plan_slogan', models.CharField(max_length=255)),
            ],
        ),
    ]
