# Generated by Django 3.2 on 2021-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('contact_1', models.IntegerField()),
                ('contact_2', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('plans', models.CharField(max_length=200)),
            ],
        ),
    ]
